name: "NugetVersionTest"

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-push:
    name: "NugetVersionTest"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build --configuration Release 

      - name: Test
        run: dotnet test --configuration Release --no-build      
